"""
Database Configuration File
Define your database structures here
"""

# Database-specific excluded keywords for special character validation
# These fields will be excluded from special character validation for each database
# Format: {database_name: [list of keywords to exclude]}
EXCLUDED_KEYWORDS = {
    "Liceptor Database": ['helm', 'smiles', 'smile', 'molstructure', 'molstructures','affinity','id','unit'],
    "Pharmacokinetic Database": ['helm', 'smiles', 'smile', 'molstructure', 'molstructures',  'application_attribute', 'receptor','type','calculated_boilingpoint','calculated_meltingpoint','pk_vitro_dose','pk_vitro_unit','pk_vivo_dose','pk_vivo_unit','physchem_comments','physchem_material','physchem_unit','salt','str_comments'],
    "Microsomal Stability Database": ['helm', 'smiles', 'smile', 'molstructure', 'molstructures', 'application_attribute','compound_status','calculated_boilingpoint','calculated_meltingpoint'],
    "Antibody Drug Conjugate (ADC) Database": ['helm', 'smiles', 'smile', 'molstructure', 'molstructures','Linker structure','Drug structure','Drug linker structure','LINKERSTRUCTURE_SMILES','DRUG_LINKER_STRUCTURE_SMILES','HELM sequence','Modification in SMILES'],
    "Theme Database": ['helm', 'smiles', 'smile', 'molstructure', 'molstructures'],
    "Biomarker Genomic/Molecular Alteration Module": ['helm', 'smiles', 'smile', 'molstructure', 'molstructures'],
    "Investigational and Approved Therapeutics Module": ['helm', 'smiles', 'smile', 'molstructure', 'molstructures'],
    "Clinical trials Module": ['helm', 'smiles', 'smile', 'molstructure', 'molstructures', 'Exclusion Criteria','Inclusion Criteria','Phase','Purpose'],
    "Protein Degradation Database (Proximers Database)": ['helm', 'smiles', 'smile', 'molstructure', 'molstructures', 'linker_structure','pbm_structure','ubm_structure','pd_structure'],
    "Spectra Database": ['helm', 'smiles', 'smile', 'molstructure', 'molstructures','13C_NMR','1H_NMR','19F_NMR','IR'],
    "Peptide Database": ['helm', 'smiles', 'smile', 'molstructure', 'molstructures']
    # Add more databases as needed
    # "Database Name": ['keyword1', 'keyword2', ...]
}

# Database-specific special character removal configuration
# Format: {database_name: {field_name: [list of special characters to remove]}}
# Example: Remove '@' and '#' from 'email' field in 'User Database'
# SPECIAL_CHAR_REMOVAL = {
#     "Database Name": {
#         "field_name": ['@', '#', '$'],
#         "another_field": ['%', '&']
#     }
# }
SPECIAL_CHAR_REMOVAL = {
    # Example configuration (uncomment and modify as needed):
    # "Liceptor Database": {
    #     "COMMENTS": ['@', '#', '$'],  # Remove @, #, $ from COMMENTS field
    #     "REFERENCE": ['%', '&']       # Remove %, & from REFERENCE field
    # },
    # "Pharmacokinetic Database": {
    #     "PK_VITRO_COMMENTS": ['@', '#'],
    #     "PK_VIVO_COMMENTS": ['$', '%']
    # }
    # Add more databases and fields as needed
}

# Define your databases, tables, and fields here
DATABASES = {
    "Liceptor Database": [
        "MolStructure",
        "ID",
        "SALT",
        "STR_COMMENTS",
        "RECEPTOR",
        "TYPE",
        "MEASURE",
        "AFFINITY",
        "UNIT",
        "UNIFIEDVALUE",
        "ASSAY",
        "FUNCTION",
        "ORGANISM",
        "THERAPEUTIC DATA",
        "REFERENCE",
        "SOURCE",
        "YEAR",
        "COMMENTS",
        "UNIPROT"
    ],

    "Pharmacokinetic Database": {
        # under annexure we are using IN VITRO, IN VIVO, Physico-Chemical Properties
        #  under delivery JSON we are in_vitro_bioactivity, in_vivo_bioactivity, phys_chem_data
        "in_vitro_bioactivity": [
            "MolStructure",
            "GENERIC_NAME",
            "CODE_NAME",
            "BRAND_NAME",
            "SYNONYM",
            "STR_COMMENTS",
            "SALT",
            "THERAPEUTIC_DATA",
            "CALCULATED_MOLECULARFORMULA",
            "CALCULATED_MOLECULARWEIGHT",
            "CALCULATED_LOGP",
            "CALCULATED_MELTINGPOINT",
            "CALCULATED_BOILINGPOINT",
            "APPLICATION ATTRIBUTE",
            "ADDITIONAL_MOLECULAR DESCRIPTORS",
            "FRAGMENT_SIMILARITY",
            "RECEPTOR",
            "TYPE",
            "FUNCTION",
            "ORGANISM",
            "PK_VITRO_PARAMETER",
            "PK_VITRO_PARAMETER_MIN",
            "PK_VITRO_PARAMETER_MAX",
            "PK_VITRO_UNIT",
            "PK_VITRO_STD_ PARAMETER_MIN",
            "PK_VITRO_STD_ PARAMETER_MAX",
            "PK_VITRO_STDUNIT",
            "PK_VITRO_ASSAY",
            "ORGANISM",
            "PK_VITRO_MATERIAL",
            "PK_VITRO_COMMENTS",
            "PK_VITRO_COMPOUND_STATUS",
            "PK_VITRO_ASSAY_LENGTH_TIME_(MIN)",
            "PK_VITRO_DOSE"
        ],
        "in_vivo_bioactivity": [
            "PK_VIVO_PARAMETER",
            "PK_VIVO_PARAMETER_MIN",
            "PK_VIVO_PARAMETER_MAX",
            "PK_VIVO_UNIT",
            "PK_VIVO_STD_ PARAMETER_MIN",
            "PK_VIVO_STD_ PARAMETER_MAX",
            "PK_VIVO_STDUNIT",
            "PK_VIVO_ANIMALMODEL",
            "PK_VIVO_ROUTE",
            "PK_VIVO_DOSE",
            "PK_VIVO_COMMENTS"
        ],
        "phys_chem_data": [
            "PHYSCHEM_PARAMETER",
            "PHYSCHEM _PARAMETER_MIN",
            "PHYSCHEM _PARAMETER_MAX",
            "PHYSCHEM_UNIT",
            "PHYSCHEM _STD_ PARAMETER_MIN",
            "PHYSCHEM _STD_ PARAMETER_MAX",
            "PHYSCHEM_STDUNIT",
            "PHYSCHEM_MATERIAL",
            "PHYSCHEM_COMMENTS"
        ]
    },
    "Microsomal Stability Database": [
        "MolStructure",
        "GENERIC_NAME",
        "CODE_NAME",
        "BRAND_NAME",
        "SYNONYM",
        "STR_COMMENTS",
        "SALT",
        "CALCULATED_MOLECULARFORMULA",
        "CALCULATED_MOLECULARWEIGHT",
        "CALCULATED_LOGP",
        "CALCULATED_MELTINGPOINT",
        "MODE_ACTION",
        "MEASURE",
        "MEASURE_MIN",
        "MEASURE_MAX",
        "UNIT",
        "ASSAY",
        "ORGANISM",
        "MATERIAL",
        "COMPOUND_STATUS",
        "ASSAY_LENGTH_TIME_(MIN)",
        "DOSE",
        "FRAGMENT_SIMILARITY",
        "ADDITIONAL_MOLECULAR DESCRIPTORS",
        "THERAPEUTIC_DATA",
        "APPLICATION ATTRIBUTE"
    ],
    
    "Antibody Drug Conjugate (ADC) Database": [
        "LinkerID",
            "Linker type",
            "Linker cleavable type",
            "Linker cleavable type",
            "Linker molecular formula",
            "Linker structure",
            "Linker sequence",
            "Drug ID",
            "Drug chemical family",
            "Drug salt",
            "Drug molecular weight",
            "Drug molecular formula",
            "Drug structure",
            "Drug linker ID",
            "Drug linker molecular weight",
            "Drug linker molecular formula",
            "Drug linker structure",
            "ADC ID",
            "DAR",
            "Antibody ID",
            "Type",
            "Subtype",
            "Sequence ID",
            "Moiety",
            "Sequence",
            "FASTA",
            "Modification",
            "Modification in SMILES",
            "Position",
            "HELM sequence",
            "Cyclization position",
            "Cyclization type",
            "Disease name",
            "Family",
            "Name",
            "Domain",
            "Molecular Event",
            "Molecular Event Details",
            "Organism",
            "Model",
            "Assay",
            "Assay organism",
            "Cell line",
            "Cell type",
            "Organ",
            "Dose_Abs value",
            "Dose_Min value",
            "Dose_max value",
            "Dose_unit",
            "Route of administration",
            "Time duration_Absolute value",
            "Time duration_Absolute value",
            "Time duration_max value",
            "Time duration_unit",
            "Metabolic enzyme",
            "Other assay conditions",
            "Parameter",
            "Abs value",
            "Min value",
            "Max value",
            "Unit",
            "Standard error",
            "Standard deviation",
            "Action",
            "Bio Effects",
            "Bio Effects details"
        ],
    "Theme Database": [
        "MolStructure:BIOPATHWAY_REACTANT",
        "BIOPATHWAY_REACTANT_NAME",
        "BIOPATHWAY_REACTANT_MOLFORMULA",
        "BIOPATHWAY_REACTANT_MOLWEIGHT",
        "DRUG_NAME",
        "ROUTE_OF_ADMINISTRATION",
        "MolStructure:BIOPATHWAY_PRODUCT",
        "BIOPATHWAY_PRODUCT_NAME",
        "BIOPATHWAY_PRODUCT_MOLFORMULA",
        "BIOPATHWAY_PRODUCT_MOLWEIGHT",
        "BIOPATHWAYPRODUCT:ENZYME",
        "BIOPATHWAYPRODUCT:REACTION_TYPE",
        "BIOPATHWAYPRODUCT:ASSAY",
        "BIOPATHWAYPRODUCT:SIGNALING_MOIETY",
        "BIOPATHWAYPRODUCT:KM_VALUE",
        "BIOPATHWAYPRODUCT:METABOLITE_SYSTEM",
        "BIOPATHWAYPRODUCT:ORGANISM",
        "BIOPATHWAYPRODUCT:MATERIAL",
        "BIOPATHWAYPRODUCT:ORGAN_SYSTEM",
        "UNIPROT",
        "ENZYME COMMISSION NUMBER",
        "COMBINATION_DRUG",
        "PRODUCT_OCCURANCE",
        "PRODUCT_OCCURANCE_PERCENTAGE",
        "PRODUCT_OCCURANCE_ORGANISM",
        "PRODUCT_OCCURANCE_MATERIAL",
        "DOSE",
        "UNIT",
        "Toxicity"
    ],
    "Biomarker Genomic/Molecular Alteration Module": [
        "Nature of study",
        "Disease classifier 1",
        "Disease classifier 2",
        "Disease classifier 3",
        "Disease classifier 4",
        "Disease classifier 5",
        "Disease classifier 6",
        "Cancer Type",
        "Gene symbol",
        "Gene ID",
        "Molecular Alteration",
        "Molecular Alteration Type",
        "Location",
        "Exon Number",
        "Investigation technique",
        "Investigated therapy",
        "Clinical Outcome"            
    ],
    "Investigational and Approved Therapeutics Module": [
        "Drug Type",
        "Brand Name",
        "Generic Name",
        "Code Name",
        "Synonym/Other",
        "Molstructure",
        "Developer",
        "Marketer",
        "Originator",
        "Drug Class",
        "Mechanism of Action",
        "Drug Target",
        "Molecular Alteration",
        "Phase",
        "Disease",
        "Cancer type",
        "Stage",
        "FDA Approved",
        "FDA Indication",
        "Europe Approved",
        "Europe Indication",
        "Other Approvals"
    ],
    "Clinical trials Module": [
        "TrialID",
        "Title",
        "Sponsor",
        "Responsible Party",
        "Official Title",
        "Status",
        "Study Type",
        "Phase",
        "Purpose",
        "Condition",
        "Disease Status",
        "Disease Classifier 1",
        "Disease Classifier 2",
        "Disease Classifier 3",
        "Disease Classifier 4",
        "Disease Classifier 5",
        "Disease Classifier 6",
        "Primary Interventions",
        "Other Interventions",
        "Detailed Description",
        "Location Name",
        "Location City",
        "Location State",
        "Location Country",
        "Inclusion Criteria",
        "Inclusion Gene/s",
        "Inclusion Gene/s Status",
        "Exclusion Criteria",
        "Exclusion Gene/s",
        "Exclusion Gene/s Status",
        "Age In Years",
        "Gender"
    ],
   
    # "Protein Degradation Database (Proximers Database)": {
    #     "Therapeutic_Area": [
    #         "Therapeutic_Area",
    #         "Disease_Indication"
    #     ],
    #     "Linker": [
    #         "Linker_Structure",
    #         "Linker_type",
    #         "Linker_connector_atoms",
    #         "Linker_Nomenclature",
    #         "Linker_Formula",
    #         "Linker_TPSA",
    #         "Linker_cLogP",
    #         "Linker_Molecular_weight"
    #     ],
    #     "PBM": [
    #         "PBM_Structure",
    #         "PBM_Formula",
    #         "PBM_Pubchem_CID",
    #         "PBM_TPSA",
    #         "PBM_Molecular_Weight",
    #         "PBM_cLogP",
    #         "PBM_Smiles",
    #         "PBM_Nomenclature"
    #     ],
    #     "PBM_Activity": [
    #         "PBM_Target",
    #         "PBM_Target_Molecular_Event",
    #         "PBM_Target_Molecular_Event_Details",
    #         "PBM_Target_Domain",
    #         "PBM_Target_Construct",
    #         "PBM_Target_Uniprot_ID",
    #         "PBM_Cellular_material_used",
    #         "PBM_Experimental_technique",
    #         "PBM_Parameter",
    #         "PBM_Parameter_AbsValue",
    #         "PBM_Parameter_RangeValue_min",
    #         "PBM_Parameter_RangeValue_max",
    #         "PBM_Parameter_Unit",
    #         "PBM_Parameter_StdAbsValue",
    #         "PBM_Parameter_StdRangeValue_min",
    #         "PBM_Parameter_StdRangeValue_max",
    #         "PBM_Parameter_StdUnit"
    #     ],
    #     "UBM": [
    #         "UBM_Nomenclature",
    #         "UBM_Formula",
    #         "UBM_Structure",
    #         "UBM_Molecular_Weight",
    #         "UBM_Pubchem_CID",
    #         "UBM_TPSA",
    #         "UBM_cLogP",
    #         "UBM_Smiles"
    #     ],
    #     "UBM_Activity": [
    #         "UBM_Parameter",
    #         "UBM_Parameter_AbsValue",
    #         "UBM_Parameter_RangeValue_min",
    #         "UBM_Parameter_RangeValue_max",
    #         "UBM_Parameter_Unit",
    #         "UBM_Parameter_StdAbsValue",
    #         "UBM_Parameter_StdRangeValue_min",
    #         "UBM_Parameter_StdRangeValue_max",
    #         "UBM_Parameter_StdUnit"
    #     ],
    #     "PD": [
    #         "PD_Structure",
    #         "PD_nomenclature",
    #         "PD_Pubchem_ID",
    #         "PD_Formula",
    #         "PD_Molecular_weight",
    #         "PD_Smiles",
    #         "PD_TPSA",
    #         "PD_cLogP",
    #         "PD_NMR",
    #         "PD_LCMS",
    #         "PD_Hydrogen_Bond_Donor",
    #         "PD_Hydrogen_Bond_Acceptor"
    #     ],
    #     "PD_Data": [
    #         "PD_Target",
    #         "PD_Target_Molecular_Event",
    #         "PD_Target_Molecular_Event_Details",
    #         "PD_Target_Domain",
    #         "PD_Target_Construct",
    #         "PD_Target_Uniprot_ID",
    #         "PD_percentTarget_remaining_Abs",
    #         "PD_percentTarget_remaining_Min",
    #         "PD_percentTarget_remaining_Max",
    #         "PD_Target_effect",
    #         "PD_Target_effect_measure_Abs",
    #         "PD_Target_effect_measure_Min",
    #         "PD_Target_effect_measure_Max",
    #         "PD_Target_effect_unit",
    #         "PD_Target_exposure",
    #         "PD_Target_exposure_unit",
    #         "PD_Parameter",
    #         "PD_Parameter_Abs_Value",
    #         "PD_Parameter_RangeValue_min",
    #         "PD_Parameter_RangeValue_max",
    #         "PD_Parameter_Unit",
    #         "PD_Parameter_StdAbs_Value",
    #         "PD_Parameter_StdRangeValue_min",
    #         "PD_Parameter_StdRangeValue_max",
    #         "PD_Parameter_StdUnit"
    #     ],
    #     "PD_Degradation": [
    #         "PD_Degradation_Mechanism",
    #         "PD_DegradationMechanismsubtyp"
    #     ],
    #     "PD_In_vitro": [
    #         "PD_Target",
    #         "PD_Target_Molecular_Event",
    #         "PD_Target_Molecular_Event_Details",
    #         "PD_Target_Domain",
    #         "PD_Target_Construct",
    #         "PD_Target_Uniprot_ID",
    #         "PD_percentTarget_remaining_Abs",
    #         "PD_percentTarget_remaining_Min",
    #         "PD_percentTarget_remaining_Max",
    #         "PD_Target_effect",
    #         "PD_Target_effect_measure_Abs",
    #         "PD_Target_effect_measure_Min",
    #         "PD_Target_effect_measure_Max",
    #         "PD_Target_effect_unit",
    #         "PD_Target_exposure",
    #         "PD_Target_exposure_unit",
    #         "PD_Parameter",
    #         "PD_Parameter_Abs_Value",
    #         "PD_Parameter_RangeValue_min",
    #         "PD_Parameter_RangeValue_max",
    #         "PD_Parameter_Unit",
    #         "PD_Parameter_StdAbs_Value",
    #         "PD_Parameter_StdRangeValue_min",
    #         "PD_Parameter_StdRangeValue_max",
    #         "PD_Parameter_StdUnit",
    #         "PD_Cellular_material_used",
    #         "PD_Experimental_technique",
    #         "PD_Absolute_Dose",
    #         "PD_Dose_Range_Value_min",
    #         "PD_Dose_Range_Value_max",
    #         "PD_Dose_Unit",
    #         "PD_In_vitro_In_BioEffect_Activity",
    #         "PD_Biological_effects",
    #         "PD_Biological_effects_details"
    #     ],
    #     "PD_In_vivo": [
    #         "PD_Target",
    #         "PD_Target_Molecular_Event",
    #         "PD_Target_Molecular_Event_Details",
    #         "PD_Target_Domain",
    #         "PD_Target_Construct",
    #         "PD_Target_Uniprot_ID",
    #         "PD_percentTarget_remaining_Abs",
    #         "PD_percentTarget_remaining_Min",
    #         "PD_percentTarget_remaining_Max",
    #         "PD_Target_effect",
    #         "PD_Target_effect_measure_Abs",
    #         "PD_Target_effect_measure_Min",
    #         "PD_Target_effect_measure_Max",
    #         "PD_Target_effect_unit",
    #         "PD_Target_exposure",
    #         "PD_Target_exposure_unit",
    #         "PD_Parameter",
    #         "PD_Parameter_Abs_Value",
    #         "PD_Parameter_RangeValue_min",
    #         "PD_Parameter_RangeValue_max",
    #         "PD_Parameter_Unit",
    #         "PD_Parameter_StdAbs_Value",
    #         "PD_Parameter_StdRangeValue_min",
    #         "PD_Parameter_StdRangeValue_max",
    #         "PD_Parameter_StdUnit",
    #         "PD_Assay_Organism",
    #         "PD_Cellular_material_used",
    #         "PD_Experimental_technique",
    #         "PD_Assay_RouteAdministration",
    #         "PD_Assay_Absolute_Dose",
    #         "PD_Dose_Range_Value_min",
    #         "PD_Dose_Range_Value_max",
    #         "PD_Assay_Dose_Unit",
    #         "PD_In_vivo_In_BioEffect_Activity",
    #         "PD_Biological_effects",
    #         "PD_Biological_effects_details"
    #     ],
    #     "PD_PK": [
    #         "PD_PK_Target",
    #         "PD_PK_Target_Molecular_Event",
    #         "PD__PK_Target_Molecular_Event_Details",
    #         "PD_PK_Target_Domain",
    #         "PD_Target_Construct",
    #         "PD_Target_Uniprot_ID",
    #         "PD_PK_Cellular_material_used",
    #         "PD_PK_Experimental_technique",
    #         "PD_PK_Parameter",
    #         "PD_PK_Parameter_Abs_Value",
    #         "PD_PK_Parameter_RangeValue_min",
    #         "PD_PK_Parameter_RangeValue_max",
    #         "PD_PK_Parameter_Unit",
    #         "PD_PK_Parameter_StdAbs_Value",
    #         "PD_PK_Parameter_StdRangeValue_min",
    #         "PD_PK_Parameter_StdRangeValue_max",
    #         "PD_PK_Parameter_StdUnit",
    #         "PD_PK_ParameterOrganismused",
    #         "PD_PK_RouteAdministration",
    #         "PD_PK_Absolute_Dose",
    #         "PD_PK_Dose_Range_Value_min",
    #         "PD_PK_Dose_Range_Value_min",
    #         "PD_PK_Dose_Unit"
    #     ],
    #     "PD_Subtype": [
    #         "PD_Subtype",
    #         "PD_Subtype_Detail"
    #     ],
    #     "PD_Ubiquitin_Ligase_involved": [
    #         "PD_Ubiquitin_Ligase_involved",
    #         "PD_ Ligase_Parameter",
    #         "PD_Ligase_ParameterAbsValue",
    #         "PD_Ligase_Parameter_RangeValue_min",
    #         "PD__Ligase_Parameter_RangeValue_max",
    #         "PD_Ligase_Parameter_Unit",
    #         "PD_Ligase_Parameter_StdAbsValue",
    #         "PD_Ligase_Parameter_StdRangeValue_min",
    #         "PD_Ligase_Parameter_StdRangeValue_max",
    #         "PD_Ligase_Parameter_StdUnit"
    #     ],
    #     "Photolabile": [
    #         "Photolabile_Irradiationmeasure",
    #         "Photolabile_Irradiationmeasure_unit",
    #         "Photolabile_Irradiation_dur",
    #         "Photolabile_Irradiation_dur_unit",
    #         "Photolabile_group_structure",
    #         "Photolabile_formula",
    #         "Photolabile_Pubchem_CID",
    #         "Photolabile_nomenclature",
    #         "Photolabile_smiles",
    #         "Photolabile_Molecular_weight"
    #     ]
    # },


    "Protein Degradation Database (Proximers Database)": {
        "Therapeutic_Area": "",
        "Disease_Indication": "",
        "Linker_Structure": "",
        "Linker_type": "",
        "Linker_connector_atoms": "",
        "Linker_Nomenclature": "",
        "Linker_Formula": "",
        "Linker_TPSA": "",
        "Linker_cLogP": "",
        "Linker_Molecular_weight": "",
        "PBM_Structure": "",
        "PBM_Formula": "",
        "PBM_Pubchem_CID": "",
        "PBM_TPSA": "",
        "PBM_Molecular_Weight": "",
        "PBM_cLogP": "",
        "PBM_Smiles": "",
        "PBM_Nomenclature": "",
        "PBM_Target": "",
        "PBM_Target_Molecular_Event": "",
        "PBM_Target_Molecular_Event_Details": "",
        "PBM_Target_Domain": "",
        "PBM_Target_Construct": "",
        "PBM_Target_Uniprot_ID": "",
        "PBM_Cellular_material_used": "",
        "PBM_Experimental_technique": "",
        "PBM_Parameter": "",
        "PBM_Parameter_AbsValue": "",
        "PBM_Parameter_RangeValue_min": "",
        "PBM_Parameter_RangeValue_max": "",
        "PBM_Parameter_Unit": "",
        "PBM_Parameter_StdAbsValue": "",
        "PBM_Parameter_StdRangeValue_min": "",
        "PBM_Parameter_StdRangeValue_max": "",
        "PBM_Parameter_StdUnit": "",
        "UBM_Nomenclature": "",
        "UBM_Formula": "",
        "UBM_Structure": "",
        "UBM_Molecular_Weight": "",
        "UBM_Pubchem_CID": "",
        "UBM_TPSA": "",
        "UBM_cLogP": "",
        "UBM_Smiles": "",
        "UBM_Parameter": "",
        "UBM_Parameter_AbsValue": "",
        "UBM_Parameter_RangeValue_min": "",
        "UBM_Parameter_RangeValue_max": "",
        "UBM_Parameter_Unit": "",
        "UBM_Parameter_StdAbsValue": "",
        "UBM_Parameter_StdRangeValue_min": "",
        "UBM_Parameter_StdRangeValue_max": "",
        "UBM_Parameter_StdUnit": "",
        "PD_Structure": "",
        "PD_nomenclature": "",
        "PD_Pubchem_ID": "",
        "PD_Formula": "",
        "PD_Molecular_weight": "",
        "PD_Smiles": "",
        "PD_TPSA": "",
        "PD_cLogP": "",
        "PD_NMR": "",
        "PD_LCMS": "",
        "PD_Hydrogen_Bond_Donor": "",
        "PD_Hydrogen_Bond_Acceptor": "",
        "PD_Data": [
        "PD_Target",
        "PD_Target_Molecular_Event",
        "PD_Target_Molecular_Event_Details",
        "PD_Target_Domain",
        "PD_Target_Construct",
        "PD_Target_Uniprot_ID",
        "PD_percentTarget_remaining_Abs",
        "PD_percentTarget_remaining_Min",
        "PD_percentTarget_remaining_Max",
        "PD_Target_effect",
        "PD_Target_effect_measure",
        "PD_Target_effect_unit",
        "PD_Target_exposure",
        "PD_Target_exposure_unit",
        "PD_Parameter",
        "PD_Parameter_Abs_Value",
        "PD_Parameter_RangeValue_min",
        "PD_Parameter_RangeValue_max",
        "PD_Parameter_Unit",
        "PD_Parameter_StdAbs_Value",
        "PD_Parameter_StdRangeValue_min",
        "PD_Parameter_StdRangeValue_max",
        "PD_Parameter_StdUnit"
        ],
        "PD_Degradation": [
        "PD_Degradation_Mechanism",
        "PD_DegradationMechanismsubtyp"
        ],
        "PD_In_vitro": [
        "PD_Target",
        "PD_Target_Molecular_Event",
        "PD_Target_Molecular_Event_Details",
        "PD_Target_Domain",
        "PD_Target_Construct",
        "PD_Target_Uniprot_ID",
        "PD_percentTarget_remaining_Abs",
        "PD_percentTarget_remaining_Min",
        "PD_percentTarget_remaining_Max",
        "PD_Target_effect",
        "PD_Target_effect_measure",
        "PD_Target_effect_unit",
        "PD_Target_exposure",
        "PD_Target_exposure_unit",
        "PD_Parameter",
        "PD_Parameter_Abs_Value",
        "PD_Parameter_RangeValue_min",
        "PD_Parameter_RangeValue_max",
        "PD_Parameter_Unit",
        "PD_Parameter_StdAbs_Value",
        "PD_Parameter_StdRangeValue_min",
        "PD_Parameter_StdRangeValue_max",
        "PD_Parameter_StdUnit",
        "PD_Cellular_material_used",
        "PD_Experimental_technique",
        "PD_Absolute_Dose",
        "PD_Dose_Range_Value_min",
        "PD_Dose_Range_Value_max",
        "PD_Dose_Unit",
        "PD_Biological_effects",
        "PD_Biological_effects_details"
        ],
        "PD_In_vivo": [
        "PD_Target",
        "PD_Target_Molecular_Event",
        "PD_Target_Molecular_Event_Details",
        "PD_Target_Domain",
        "PD_Target_Construct",
        "PD_Target_Uniprot_ID",
        "PD_percentTarget_remaining_Abs",
        "PD_percentTarget_remaining_Min",
        "PD_percentTarget_remaining_Max",
        "PD_Target_effect",
        "PD_Target_effect_measure",
        "PD_Target_effect_unit",
        "PD_Target_exposure",
        "PD_Target_exposure_unit",
        "PD_Parameter",
        "PD_Parameter_Abs_Value",
        "PD_Parameter_RangeValue_min",
        "PD_Parameter_RangeValue_max",
        "PD_Parameter_Unit",
        "PD_Parameter_StdAbs_Value",
        "PD_Parameter_StdRangeValue_min",
        "PD_Parameter_StdRangeValue_max",
        "PD_Parameter_StdUnit",
        "PD_Assay_Organism",
        "PD_Cellular_material_used",
        "PD_Experimental_technique",
        "PD_Assay_RouteAdministration",
        "PD_Assay_Absolute_Dose",
        "PD_Dose_Range_Value_min",
        "PD_Dose_Range_Value_max",
        "PD_Assay_Dose_Unit",
        "PD_Biological_effects",
        "PD_Biological_effects_details"
        ],
        "PD_PK": [
        "PD_PK_Target",
        "PD_PK_Target_Molecular_Event",
        "PD_PK_Target_Molecular_Event_Details",
        "PD_PK_Target_Domain",
        "PD_Target_Construct",
        "PD_Target_Uniprot_ID",
        "PD_PK_Cellular_material_used",
        "PD_PK_Experimental_technique",
        "PD_PK_Parameter",
        "PD_PK_Parameter_Abs_Value",
        "PD_PK_Parameter_RangeValue_min",
        "PD_PK_Parameter_RangeValue_max",
        "PD_PK_Parameter_Unit",
        "PD_PK_Parameter_StdAbs_Value",
        "PD_PK_Parameter_StdRangeValue_min",
        "PD_PK_Parameter_StdRangeValue_max",
        "PD_PK_Parameter_StdUnit",
        "PD_PK_ParameterOrganismused",
        "PD_PK_RouteAdministration",
        "PD_PK_Absolute_Dose",
        "PD_PK_Dose_Range_Value_min",
        "PD_PK_Dose_Range_Value_max",
        "PD_PK_Dose_Unit"
        ],
        "PD_Subtype": "",
        "PD_Subtype_Detail": "",
        "PD_Ubiquitin_Ligase_involved": "",
        "PD_Ligase_Parameter": "",
        "PD_Ligase_ParameterAbsValue": "",
        "PD_Ligase_Parameter_RangeValue_min": "",
        "PD_Ligase_Parameter_RangeValue_max": "",
        "PD_Ligase_Parameter_Unit": "",
        "PD_Ligase_Parameter_StdAbsValue": "",
        "PD_Ligase_Parameter_StdRangeValue_min": "",
        "PD_Ligase_Parameter_StdRangeValue_max": "",
        "PD_Ligase_Parameter_StdUnit": "",
        "Photolabile_Irradiationmeasure": "",
        "Photolabile_Irradiationmeasure_unit": "",
        "Photolabile_Irradiation_dur": "",
        "Photolabile_Irradiation_dur_unit": "",
        "Photolabile_group_structure": "",
        "Photolabile_formula": "",
        "Photolabile_Pubchem_CID": "",
        "Photolabile_nomenclature": "",
        "Photolabile_smiles": "",
        "Photolabile_Molecular_weight": ""
    },

    # "Protein Degradation Database (Proximers Database)": {
    #     "Therapeutic_Area",
    #     "Disease_Indication",
    #     "Linker_Structure",
    #     "Linker_type",
    #     "Linker_connector_atoms",
    #     "Linker_Nomenclature",
    #     "Linker_Formula",
    #     "Linker_TPSA",
    #     "Linker_cLogP",
    #     "Linker_Molecular_weight",
    #     "PBM_Structure",
    #     "PBM_Formula",
    #     "PBM_Pubchem_CID",
    #     "PBM_TPSA",
    #     "PBM_Molecular_Weight",
    #     "PBM_cLogP",
    #     "PBM_Smiles",
    #     "PBM_Nomenclature",
    #     "PBM_Target",
    #     "PBM_Target_Molecular_Event",
    #     "PBM_Target_Molecular_Event_Details",
    #     "PBM_Target_Domain",
    #     "PBM_Target_Construct",
    #     "PBM_Target_Uniprot_ID",
    #     "PBM_Cellular_material_used",
    #     "PBM_Experimental_technique",
    #     "PBM_Parameter",
    #     "PBM_Parameter_AbsValue",
    #     "PBM_Parameter_RangeValue_min",
    #     "PBM_Parameter_RangeValue_max",
    #     "PBM_Parameter_Unit",
    #     "PBM_Parameter_StdAbsValue",
    #     "PBM_Parameter_StdRangeValue_min",
    #     "PBM_Parameter_StdRangeValue_max",
    #     "PBM_Parameter_StdUnit",
    #     "UBM_Nomenclature",
    #     "UBM_Formula",
    #     "UBM_Structure",
    #     "UBM_Molecular_Weight",
    #     "UBM_Pubchem_CID",
    #     "UBM_TPSA",
    #     "UBM_cLogP",
    #     "UBM_Smiles",
    #     "UBM_Parameter",
    #     "UBM_Parameter_AbsValue",
    #     "UBM_Parameter_RangeValue_min",
    #     "UBM_Parameter_RangeValue_max",
    #     "UBM_Parameter_Unit",
    #     "UBM_Parameter_StdAbsValue",
    #     "UBM_Parameter_StdRangeValue_min",
    #     "UBM_Parameter_StdRangeValue_max",
    #     "UBM_Parameter_StdUnit",
    #     "PD_Structure",
    #     "PD_nomenclature",
    #     "PD_Pubchem_ID",
    #     "PD_Formula",
    #     "PD_Molecular_weight",
    #     "PD_Smiles",
    #     "PD_TPSA",
    #     "PD_cLogP",
    #     "PD_NMR",
    #     "PD_LCMS",
    #     "PD_Hydrogen_Bond_Donor",
    #     "PD_Hydrogen_Bond_Acceptor",
    #     "PD_Data": [
    #         "PD_Target",
    #         "PD_Target_Molecular_Event",
    #         "PD_Target_Molecular_Event_Details",
    #         "PD_Target_Domain",
    #         "PD_Target_Construct",
    #         "PD_Target_Uniprot_ID",
    #         "PD_percentTarget_remaining_Abs",
    #         "PD_percentTarget_remaining_Min",
    #         "PD_percentTarget_remaining_Max",
    #         "PD_Target_effect",
    #         "PD_Target_effect_measure_Abs",
    #         "PD_Target_effect_measure_Min",
    #         "PD_Target_effect_measure_Max",
    #         "PD_Target_effect_unit",
    #         "PD_Target_exposure",
    #         "PD_Target_exposure_unit",
    #         "PD_Parameter",
    #         "PD_Parameter_Abs_Value",
    #         "PD_Parameter_RangeValue_min",
    #         "PD_Parameter_RangeValue_max",
    #         "PD_Parameter_Unit",
    #         "PD_Parameter_StdAbs_Value",
    #         "PD_Parameter_StdRangeValue_min",
    #         "PD_Parameter_StdRangeValue_max",
    #         "PD_Parameter_StdUnit"
    #     ],
    #     "PD_Degradation": [
    #         "PD_Degradation_Mechanism",
    #         "PD_DegradationMechanismsubtyp"
    #     ],
    #     "PD_In_vitro": [
    #         "PD_Target",
    #         "PD_Target_Molecular_Event",
    #         "PD_Target_Molecular_Event_Details",
    #         "PD_Target_Domain",
    #         "PD_Target_Construct",
    #         "PD_Target_Uniprot_ID",
    #         "PD_percentTarget_remaining_Abs",
    #         "PD_percentTarget_remaining_Min",
    #         "PD_percentTarget_remaining_Max",
    #         "PD_Target_effect",
    #         "PD_Target_effect_measure",
    #         "PD_Target_effect_unit",
    #         "PD_Target_exposure",
    #         "PD_Target_exposure_unit",
    #         "PD_Parameter",
    #         "PD_Parameter_Abs_Value",
    #         "PD_Parameter_RangeValue_min",
    #         "PD_Parameter_RangeValue_max",
    #         "PD_Parameter_Unit",
    #         "PD_Parameter_StdAbs_Value",
    #         "PD_Parameter_StdRangeValue_min",
    #         "PD_Parameter_StdRangeValue_max",
    #         "PD_Parameter_StdUnit",
    #         "PD_Cellular_material_used",
    #         "PD_Experimental_technique",
    #         "PD_Absolute_Dose",
    #         "PD_Dose_Range_Value_min",
    #         "PD_Dose_Range_Value_max",
    #         "PD_Dose_Unit",
    #         "PD_In_vitro_In_BioEffect_Activity",
    #         "PD_Biological_effects",
    #         "PD_Biological_effects_details"
    #     ],
    #     "PD_In_vivo": [
    #         "PD_Target",
    #         "PD_Target_Molecular_Event",
    #         "PD_Target_Molecular_Event_Details",
    #         "PD_Target_Domain",
    #         "PD_Target_Construct",
    #         "PD_Target_Uniprot_ID",
    #         "PD_percentTarget_remaining_Abs",
    #         "PD_percentTarget_remaining_Min",
    #         "PD_percentTarget_remaining_Max",
    #         "PD_Target_effect",
    #         "PD_Target_effect_measure",
    #         "PD_Target_effect_unit",
    #         "PD_Target_exposure",
    #         "PD_Target_exposure_unit",
    #         "PD_Parameter",
    #         "PD_Parameter_Abs_Value",
    #         "PD_Parameter_RangeValue_min",
    #         "PD_Parameter_RangeValue_max",
    #         "PD_Parameter_Unit",
    #         "PD_Parameter_StdAbs_Value",
    #         "PD_Parameter_StdRangeValue_min",
    #         "PD_Parameter_StdRangeValue_max",
    #         "PD_Parameter_StdUnit",
    #         "PD_Assay_Organism",
    #         "PD_Cellular_material_used",
    #         "PD_Experimental_technique",
    #         "PD_Assay_RouteAdministration",
    #         "PD_Assay_Absolute_Dose",
    #         "PD_Dose_Range_Value_min",
    #         "PD_Dose_Range_Value_max",
    #         "PD_Assay_Dose_Unit",
    #         "PD_In_vivo_In_BioEffect_Activity",
    #         "PD_Biological_effects",
    #         "PD_Biological_effects_details"
    #     ],
    #     "PD_PK": [
    #         "PD_PK_Target",
    #         "PD_PK_Target_Molecular_Event",
    #         "PD__PK_Target_Molecular_Event_Details",
    #         "PD_PK_Target_Domain",
    #         "PD_Target_Construct",
    #         "PD_Target_Uniprot_ID",
    #         "PD_PK_Cellular_material_used",
    #         "PD_PK_Experimental_technique",
    #         "PD_PK_Parameter",
    #         "PD_PK_Parameter_Abs_Value",
    #         "PD_PK_Parameter_RangeValue_min",
    #         "PD_PK_Parameter_RangeValue_max",
    #         "PD_PK_Parameter_Unit",
    #         "PD_PK_Parameter_StdAbs_Value",
    #         "PD_PK_Parameter_StdRangeValue_min",
    #         "PD_PK_Parameter_StdRangeValue_max",
    #         "PD_PK_Parameter_StdUnit",
    #         "PD_PK_ParameterOrganismused",
    #         "PD_PK_RouteAdministration",
    #         "PD_PK_Absolute_Dose",
    #         "PD_PK_Dose_Range_Value_min",
    #         "PD_PK_Dose_Range_Value_min",
    #         "PD_PK_Dose_Unit"
    #     ],
    #     "PD_Subtype",
    #     "PD_Subtype_Detail",
    #     "PD_Ubiquitin_Ligase_involved",
    #     "PD_ Ligase_Parameter",
    #     "PD_Ligase_ParameterAbsValue",
    #     "PD_Ligase_Parameter_RangeValue_min",
    #     "PD__Ligase_Parameter_RangeValue_max",
    #     "PD_Ligase_Parameter_Unit",
    #     "PD_Ligase_Parameter_StdAbsValue",
    #     "PD_Ligase_Parameter_StdRangeValue_min",
    #     "PD_Ligase_Parameter_StdRangeValue_max",
    #     "PD_Ligase_Parameter_StdUnit",
    #     "Photolabile_Irradiationmeasure",
    #     "Photolabile_Irradiationmeasure_unit",
    #     "Photolabile_Irradiation_dur",
    #     "Photolabile_Irradiation_dur_unit",
    #     "Photolabile_group_structure",
    #     "Photolabile_formula",
    #     "Photolabile_Pubchem_CID",
    #     "Photolabile_nomenclature",
    #     "Photolabile_smiles",
    #     "Photolabile_Molecular_weight"
        
    # },
    "Spectra Database": [
        "MolStructure",
        "SMILES",
        "MOL_ID",
        "SALT",
        "STR_COMMENTS",
        "1H_NMR",
        "13C_NMR",
        "19F_NMR",
        "IR",
        # "MS",
        "REFERENCE",
        "Source",
        "Year"
    ],
    "Peptide Database": [
        "ID",
        "Sequence ID",
        "Moiety",
        "Sequence",
        "FASTA",
        "Modification",
        "Modification in SMILES",
        "Position",
        "HELM sequence",
        "Cyclization position",
        "Cyclization type",
        "Family",
        "Target Name",
        "Domain",
        "Molecular Event",
        "Molecular Event Details",
        "Target Organism",
        "Disease name",
        "Model",
        "Assay",
        "Assay organism",
        "Cell line",
        "Cell type",
        "Organ",
        "Dose_Abs value",
        "Dose_Min value",
        "Dose_max value",
        "Dose_unit",
        "Route of administration",
        "Time duration_Absolute value",
        "Time duration_min value",
        "Time duration_max value",
        "Time duration_unit",
        "Metabolic enzyme",
        "Other assay conditions",
        "Parameter",
        "Abs value",
        "Min value",
        "Max value",
        "Unit",
        "Standard error",
        "Standard deviation",
        "Action",
        "Bio Effects",
        "Bio Effects details"
    ]
}


def get_databases():
    """
    Function to return database structure
    This function can be imported and used by FieldLoader
    """
    return DATABASES

